- 👋 Hi, I’m @khushii-i
- 🔭 I’m currently working on honing my Web development skills and building cool web projects.
- 🌱 I’m continously learning and exploring new web technologies and frameworks.
- ☁️ Ask me about web development or anything related to tech and coding.
- 📫 You can reach me via email at Khushibhandari0909@gmail.com
